Task_1_1_1
djennirr/OOP pull request #5
Opened 2024-09-08 15:45 UTC by djennirr

2024-09-08 15:54 UTC, galinabykova requested changes
замечания [тут](https://github.com/djennirr/OOP/pull/4) (мне их немного лень дублировать)

2024-09-09 02:25 UTC, galinabykova requested changes
ненужные файлики не удалены)
всякие .class и .jar (за исключением gradle-wrapper.jar) надо удалить
если ты удалял их из директории, этого недостаточно, нужно удалять через git rm

2024-09-09 08:13 UTC, djennirr commented
Удалил .class и .jar файлы, а также репорты консольного junit (.xml файлы)

2024-09-09 08:38 UTC, galinabykova approved these changes

2024-09-09 09:02 UTC, merged