Task_1_1_3
djennirr/OOP pull request #7
Opened 2024-09-30 05:32 UTC by djennirr

2024-09-30 12:44 UTC, djennirr commented
Потом добавлю более сложные тесты, которые включают вложенные выражения, пока там просто микротестики, которые дают понять, что вроде что-то работает и все живы

2024-09-30 15:49 UTC, galinabykova requested changes
у тебя всё очень хорошо, жду следующей версии)

2024-09-30 15:49 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/dubrovin/Variable.java
> +    public double eval(HashMap<String, Double> evaluation) {
а что будет происходить, если в словаре нет переменной?

2024-09-30 15:49 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/dubrovin/VariableTest.java
> +class VariableTest {
можно добавить тест на Evaluate, в котором нет нужно переменной в словаре

2024-09-30 15:49 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/dubrovin/Add.java
> +    private Expression firstArg;
можно добавить final

2024-12-16 05:22 UTC, galinabykova requested changes

2024-12-16 05:22 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/dubrovin/Parser.java
> +            throw new Exception("Empty expression");
лучше использовать более специализированный тип исключения, например, можешь создать свой класс исключительных ситуаций

2024-12-16 05:22 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/dubrovin/ParserTest.java
сделай сюда ещё "сложный" тест, включающий много (желательно все) операций

2024-12-16 05:22 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/dubrovin/ParserTest.java
добавь тест с  некорректным выражением

2024-12-16 05:49 UTC, djennirr commented
пока делаю доп пожалуй запрошу ревью на все остальное

2024-12-16 05:52 UTC, galinabykova requested changes
помимо описанных ранее замечаний reviewdog

2024-12-16 06:26 UTC, djennirr commented
> помимо описанных ранее замечаний reviewdog

Ой, простите, не увидел сриеди окон, сейчас почистил все старое, чтоб не мешало, мб еще ребейз сделаю. Спасибо за быстрые правки, сейчас сделаю.

2024-12-16 07:02 UTC, djennirr commented
Добавил тесты побольше в парсертест (нужно ли еще побольше?) + пофиксил варнинги + сделал классы для эксепшнов + добавил тесты для эксепшнов

2024-12-16 07:28 UTC, galinabykova requested changes
тут всё хорошо, жду доп)

2024-12-20 02:43 UTC, galinabykova approved these changes

2024-12-20 02:43 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/dubrovin/AddTest.java
> +    Add firstSum = new Add(new Number(42), new Number(69));
мне кажется, лучше не инициализировать данные на все тесты без особой причины (например, долгой инициализации). Если кто-то из твоих тестов случайно изменит эти поля, искать ошибку будет сложно

2024-12-20 03:28 UTC, merged