Task_1_5_1
djennirr/OOP pull request #9
Opened 2024-12-22 12:17 UTC by djennirr

2024-12-22 16:58 UTC, djennirr commented
Окей, это смешно. Ну, то, что я в итоге потратил не полчаса, а кучу времени не очень смешно, но это потому что я дурачок, а так если выкинуть время на то чтобы разобраться с паттерном и мд это в целом не прям долго у пряморукого человека должно выходить. А так вроде классная лаба, в том плане что покрывает классный паттерн + сюда еще интерфейсы хочется (ну мне лично), МД-шники вроде как надо получаются (поэтому и тестирую с файлами, у интеллиж есть встроенный превью для них чтобы красиво было), щас доклепаю все кроме таблиц, ну и уже +- чет есть в сухом остатке, билдер вроде билдит как надо...

2024-12-22 18:52 UTC, djennirr commented
Ревью запрашиваю просто на структуру билдера (чисто на всякий, т.к. инфу о паттерне брал из хабра + ютуба), остальные элементы допишу завтра на свежую голову (энивей 3 пары до семинара по сути пустые), чтобы понимать, движусь ли я в правильном направлении (ну, оно работает как минимум)

2024-12-22 18:54 UTC, djennirr commented
P.S. потом код для блоков кода перепишу, чтобы его можно было в списках отображать (с точки зрения логики это бред, но формат позволяет так делать)

2024-12-23 03:26 UTC, galinabykova requested changes
привет, в целом, то, что нужно, я оставила мелкие правки, которые быстро заметила, но они несущественные. Движешься в нужном направлении)

2024-12-23 04:28 UTC, djennirr commented on Task_1_5_1/src/test/java/ru/nsu/dubrovin/ImageTest.java
> +        assertEquals(FileComparator.getDiffLineNumber(new File("imageTest.md"), new File(resources + "image.md")), 0);
Ну как минимум стоит использовать методы для получения ресурсов по имени, у нас проект может быть скомпилен и собран например в jar файл, но даже в таком состоянии через специальны методы можно получать к ним доступ, мне просто в моменте было лень переделывать компаратор для файла, сейчас буду менять

2024-12-23 09:33 UTC, galinabykova requested changes
крайние тестовые случаи и ревьюдог

2024-12-23 09:49 UTC, galinabykova requested changes

2024-12-23 09:49 UTC, galinabykova commented on Task_1_5_1/src/test/java/ru/nsu/dubrovin/TextTest.java
> +        file.delete();
тут есть проблема с тем, что файл не будет удалён, если будет брошено исключение

2024-12-23 09:49 UTC, galinabykova commented on Task_1_5_1/src/test/java/ru/nsu/dubrovin/CodeBlockTest.java
> +        CodeBlock codeBlock2 = CodeBlock.builder().setContent("There is no language specified\nSo, whatever").build();
дай осмысленные имена переменным

2024-12-23 09:49 UTC, galinabykova commented on Task_1_5_1/src/test/java/ru/nsu/dubrovin/TextTest.java
> +    void testText() throws IOException {
ещё у тебя везде в тестах повторяется +- один и тот же код. Можно ли это как-то исправить и есть ли в этом смысл?

2024-12-23 14:36 UTC, djennirr commented on Task_1_5_1/src/test/java/ru/nsu/dubrovin/TextTest.java
> +    void testText() throws IOException {
Ну там не так много кода одного и того же, просто открытие файла и запись в него, там основное нагромождение именно билдер вызывает, какого-то прям глубинного смысла делать отдельный метод на запись в файл как будто не прям много, как будто немного лишнее и по количеству строк не выигрывает + текущий вариант гарантирует, что будет создан пустой файл и запись будет идти в него

2024-12-23 15:17 UTC, djennirr commented
+ equals + exceptions + lists - reviewdog

2024-12-24 03:27 UTC, galinabykova requested changes
осталось вот это
![Uploading image.png…]()

2024-12-24 05:29 UTC, galinabykova approved these changes

2024-12-24 05:37 UTC, merged